repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0 # Updated by autoupdate
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: gofmt
        language: system
        types: [go]
        args: [-s, -w]

      - id: goimports
        name: goimports
        entry: goimports
        language: system
        types: [go]
        args: [-w]

      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint
        language: system
        types: [go]
        args: [run, --fix, --timeout=5m]
